// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWJFc5v-gLy8ydYfTrF28gBlhYCPQOQ2E',
    appId: '1:771072297306:web:f63ee9b7fe5f46a5d28b63',
    messagingSenderId: '771072297306',
    projectId: 'flutter-notification-9a86f',
    authDomain: 'flutter-notification-9a86f.firebaseapp.com',
    storageBucket: 'flutter-notification-9a86f.appspot.com',
    measurementId: 'G-3GZG0DLC6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqXw19izRWoqCufGmo8Kqq_4cIxjoQ508',
    appId: '1:771072297306:android:39762adb3e4982fdd28b63',
    messagingSenderId: '771072297306',
    projectId: 'flutter-notification-9a86f',
    storageBucket: 'flutter-notification-9a86f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf6pFt0jos53kGbPBJS-H1Qrp8_zhA3S4',
    appId: '1:771072297306:ios:ab23b051b3cb6bd1d28b63',
    messagingSenderId: '771072297306',
    projectId: 'flutter-notification-9a86f',
    storageBucket: 'flutter-notification-9a86f.appspot.com',
    iosClientId: '771072297306-dvhj4qkf388vdj4ov2r3ppc38310k8if.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf6pFt0jos53kGbPBJS-H1Qrp8_zhA3S4',
    appId: '1:771072297306:ios:a18a234281ce10f9d28b63',
    messagingSenderId: '771072297306',
    projectId: 'flutter-notification-9a86f',
    storageBucket: 'flutter-notification-9a86f.appspot.com',
    iosClientId: '771072297306-g41udke1ehsgmki048752jugiooei22a.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications.RunnerTests',
  );
}
